services:
  webserver:
    container_name: rozgrywkitenisa-nginx
    image: nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend-network
      - backend-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/letsencrypt:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: always

  frontend:
    container_name: rozgrywkitenisa-frontend
    build:
      context: ./frontend
    image: rozgrywkitenisa/frontend
    env_file:
      - .env
    networks:
      - frontend-network
    restart: always

  backend:
    container_name: rozgrywkitenisa-backend
    build:
      context: ./backend
    image: rozgrywkitenisa/backend
    depends_on:
      - database
    networks:
      - frontend-network
      - backend-network
    env_file:
      - .env
    restart: always

  database:
    container_name: rozgrywkitenisa-postgres
    image: postgres
    ports:
      - "35432:5432"
    networks:
      - backend-network
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always

  certbot:
    container_name: rozgrywkitenisa-certbot
    image: certbot/certbot
    depends_on:
      - webserver
    volumes:
      - ./data/certbot/letsencrypt:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot -d $CERTBOT_DOMAIN --email $CERTBOT_EMAIL --non-interactive --agree-tos

networks:
  frontend-network:
  backend-network:
